# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-22 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsearchcondition',
            name='and_together',
            field=models.BooleanField(default=False, help_text=b'"AND" conditions together instead of "OR"'),
        ),
    ]
